services:
  - type: web
    name: ekz-library
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask --app app.py init-exam
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ekz-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: ekz-database
    plan: free
